#!/usr/bin/env bash
# Materialize an NPB-GPU problem class as a separate CUDA build directory.
#
#   tools/inputs/npb_materialize_class.sh <cg|ep|ft|is|mg> <A|C|...>
#
# The vendored Level 1 NPB ports carry cuda/npbparams.hpp generated by upstream
# sys/setparams for CLASS=B; the other classes are compile-time inputs. This
# script copies the port's CUDA sources into build/<bench>/cuda-class<X>/src,
# replaces cuda/npbparams.hpp by level1/<bench>/inputs/npbparams.<X>.hpp (the
# class-B header with the class-specific defines set to upstream's setparams
# table for class X; everything else identical) and configures/builds the copy
# exactly like the default build (level1/README.md: cmake -DBACKEND=CUDA
# -DCMAKE_BUILD_TYPE=Release). The registered class inputs point at the
# resulting binary (inputs.yaml: binary: build/<bench>/cuda-class<X>/<bench>_cuda).
# The vendored source tree and the default build directory are not touched.
set -euo pipefail
B="${1:?benchmark (cg|ep|ft|is|mg)}"; X="${2:?class letter}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; R="$(cd "$HERE/../.." && pwd)"
SRC="$R/level1/$B"; HDR="$SRC/inputs/npbparams.$X.hpp"
[ -f "$HDR" ] || { echo "npb_materialize_class: $HDR not found (no class $X header for $B)" >&2; exit 2; }
if [ "${HPC_PERFORMANCE_AI_ROOT:-}" != "$R" ] && [ -f "$R/hpcperf_env.sh" ]; then
    set +eu; # shellcheck disable=SC1091
    source "$R/hpcperf_env.sh" 2>/dev/null; set -eu
fi
OUT="$R/build/$B/cuda-class$X"; mkdir -p "$OUT/src"
# The copied CMakeLists.txt finds the tools/timing ROI header through a path relative to the
# vendored tree (../../tools/timing/roi), which does not exist next to the copy: put the header
# directory on the compilers' include path instead (the mechanism tools/timing uses for Level 2).
export CPATH="$R/tools/timing/roi${CPATH:+:$CPATH}"
rm -rf "$OUT/src/cuda" "$OUT/src/common"
cp -r "$SRC/CMakeLists.txt" "$SRC/common" "$SRC/cuda" "$OUT/src/"
cp "$HDR" "$OUT/src/cuda/npbparams.hpp"
echo "== NPB $B class $X: header $HDR -> $OUT/src/cuda/npbparams.hpp; build dir $OUT"
cmake -S "$OUT/src" -B "$OUT" -DBACKEND=CUDA -DCMAKE_BUILD_TYPE=Release ${CMAKE_GENERATOR:+-G "$CMAKE_GENERATOR"} >"$OUT/configure.log" 2>&1 || { tail -20 "$OUT/configure.log" >&2; exit 1; }
cmake --build "$OUT" -j"${MAKE_JOBS:-4}" --target "${B}_cuda" >"$OUT/build.log" 2>&1 || { tail -20 "$OUT/build.log" >&2; exit 1; }
echo "== built: $OUT/${B}_cuda"
