#!/usr/bin/env python3
"""Generate (or check) tools/timing/cases.tsv -- the Level 1 measurement case table.

The build tree is the source of truth: every benchmark's exact command line,
working directory, timeout and pass/fail regexes come from

    ctest --test-dir <build-root>/level1/<bm> --show-only=json-v1

Nine benchmarks are wrapped by a repo-authored verify.py in their add_test()
command. Timing those would measure the Python CPU reference, not the GPU work,
so the table records the INNER argv the wrapper would exec. That argv is
obtained by importing the wrapper with subprocess.run monkey-patched -- the
wrapper performs its own argv transformation (four of them rewrite arguments),
so nothing is guessed and the wrappers stay unmodified.

Paths are stored with {REPO} / {BUILD} placeholders so the table is diffable in
review and portable across build trees.

    ./gen_cases.py --build-root build/all                # write cases.tsv
    ./gen_cases.py --build-root build/all --check        # fail on drift
"""

import argparse
import json
import os
import shlex
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
DEFAULT_OUT = os.path.join(HERE, "cases.tsv")

COLUMNS = ("benchmark", "exe", "args", "cwd", "timeout_s", "wrapper", "pass_regex")

HEADER = f"""\
# tools/timing/cases.tsv -- generated by tools/timing/gen_cases.py, do not edit by hand.
# {REPO}/tools/timing/gen_cases.py --build-root <dir> --check   verifies this file against a build tree.
# exe/args/cwd use {{REPO}} (repository root) and {{BUILD}} (build root) placeholders; "-" = empty field.
# wrapper: direct = ctest runs the binary; verify.py = ctest runs a Python checker and this
#          row records the inner argv that checker execs (the binary is measured directly).
#{chr(9).join(COLUMNS)}
"""


class _Intercepted(Exception):
    """Raised by the patched subprocess.run to abort the wrapper after the first call."""

    def __init__(self, argv):
        self.argv = argv


def inner_argv_of_wrapper(wrapper_path, wrapper_argv):
    """Return the argv a verify.py wrapper would exec, without running the benchmark."""
    captured = {}

    def fake_run(cmd, *args, **kwargs):
        captured["argv"] = [str(c) for c in cmd] if isinstance(cmd, (list, tuple)) else [str(cmd)]
        raise _Intercepted(captured["argv"])

    saved_run, saved_argv, saved_path = subprocess.run, sys.argv, list(sys.path)
    subprocess.run = fake_run
    sys.argv = list(wrapper_argv)
    sys.path.insert(0, os.path.dirname(wrapper_path))
    try:
        code = compile(open(wrapper_path).read(), wrapper_path, "exec")
        exec(code, {"__name__": "__main__", "__file__": wrapper_path})
    except _Intercepted as exc:
        return exc.argv
    except SystemExit:
        pass
    except Exception as exc:  # noqa: BLE001 - the wrapper is third-party-ish; report and continue
        if "argv" in captured:
            return captured["argv"]
        raise RuntimeError(f"{wrapper_path}: could not determine inner argv ({exc})") from exc
    finally:
        subprocess.run, sys.argv = saved_run, saved_argv
        sys.path[:] = saved_path
    if "argv" in captured:
        return captured["argv"]
    raise RuntimeError(f"{wrapper_path}: wrapper never called subprocess.run")


def ctest_show(test_dir):
    """Return the parsed `ctest --show-only=json-v1` payload for one benchmark build dir."""
    proc = subprocess.run(
        ["ctest", "--test-dir", test_dir, "--show-only=json-v1"],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"ctest failed in {test_dir}: {proc.stderr.strip().splitlines()[-1:]}")
    # The login shell on this site prints lmod noise; skip anything before the JSON object.
    start = proc.stdout.find("{")
    if start < 0:
        raise RuntimeError(f"ctest produced no JSON in {test_dir}")
    return json.loads(proc.stdout[start:])


def find_benchmark_dirs(build_root):
    """Support both layouts: <root>/level1/<bm>/ (aggregate) and <root>/<bm>/cuda/ (per-benchmark)."""
    found = {}
    level1 = os.path.join(build_root, "level1")
    if os.path.isdir(level1):
        for name in sorted(os.listdir(level1)):
            d = os.path.join(level1, name)
            if os.path.isfile(os.path.join(d, "CTestTestfile.cmake")):
                found[name] = d
    if not found:
        for name in sorted(os.listdir(build_root)):
            d = os.path.join(build_root, name, "cuda")
            if os.path.isfile(os.path.join(d, "CTestTestfile.cmake")):
                found[name] = d
    return found


def placeholderize(text, build_root):
    text = text.replace(os.path.abspath(build_root), "{BUILD}")
    return text.replace(REPO, "{REPO}")


def build_rows(build_root):
    rows = []
    dirs = find_benchmark_dirs(build_root)
    if not dirs:
        raise RuntimeError(f"no benchmark build directories under {build_root}")
    for bm, test_dir in dirs.items():
        payload = ctest_show(test_dir)
        tests = payload.get("tests", [])
        if not tests:
            continue
        test = tests[0]
        command = list(test.get("command", []))
        props = {p["name"]: p["value"] for p in test.get("properties", [])}
        cwd = props.get("WORKING_DIRECTORY", test_dir)
        timeout = props.get("TIMEOUT", "")
        pass_re = props.get("PASS_REGULAR_EXPRESSION", [])
        pass_re = pass_re[0] if isinstance(pass_re, list) and pass_re else (pass_re or "")

        wrapper = "direct"
        if len(command) >= 2 and os.path.basename(command[1]) == "verify.py":
            wrapper = "verify.py"
            command = inner_argv_of_wrapper(command[1], command[1:])

        rows.append({
            "benchmark": bm,
            "exe": placeholderize(command[0], build_root),
            "args": placeholderize(" ".join(shlex.quote(a) for a in command[1:]), build_root),
            "cwd": placeholderize(cwd, build_root),
            "timeout_s": str(int(float(timeout))) if timeout else "",
            "wrapper": wrapper,
            "pass_regex": pass_re,
        })
    return rows


def render(rows):
    # "-" marks an empty field: bash's `IFS=$'\t' read` collapses runs of tabs
    # (tab is an IFS whitespace character), which would shift every later column.
    out = [HEADER.rstrip("\n")]
    for r in rows:
        out.append("\t".join((r[c] if r[c] != "" else "-") for c in COLUMNS))
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--build-root", required=True, help="CMake build tree containing the Level 1 benchmarks")
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true", help="exit 1 if the file on disk differs from the build tree")
    args = ap.parse_args()

    rows = build_rows(args.build_root)
    text = render(rows)

    if args.check:
        if not os.path.exists(args.out):
            print(f"gen_cases: {args.out} does not exist", file=sys.stderr)
            return 1
        current = open(args.out).read()
        if current != text:
            import difflib
            diff = difflib.unified_diff(current.splitlines(True), text.splitlines(True),
                                        fromfile="cases.tsv (committed)", tofile="build tree", n=1)
            sys.stderr.writelines(diff)
            print(f"gen_cases: DRIFT -- {args.out} does not match {args.build_root}", file=sys.stderr)
            return 1
        print(f"gen_cases: OK -- {len(rows)} cases match {args.build_root}")
        return 0

    with open(args.out, "w") as f:
        f.write(text)
    wrapped = sum(1 for r in rows if r["wrapper"] != "direct")
    print(f"gen_cases: wrote {args.out} ({len(rows)} cases, {wrapped} via verify.py)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
