#!/usr/bin/env python3
"""source_archives_report -- level3/SOURCE_ARCHIVES.md from the benchmark.yaml / source.lock files, the LOC
reports (provenance/LOC[.variant].json, written by tools/loc_report.py) and the equivalence reports.

    source_archives_report.py [--out level3/SOURCE_ARCHIVES.md]
"""
import argparse
import glob
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import hpcperf_source as hs  # noqa: E402

R = os.path.abspath(os.path.join(HERE, ".."))
APPS = ["lammps", "sparta", "warpx", "specfem3d", "nekrs", "nyx", "cp2k", "qmcpack", "dftfe", "geos"]


def lfs_state(path):
    if not os.path.isfile(path):
        return "absent"
    if hs.is_lfs_pointer(path):
        return "LFS pointer"
    try:
        tracked = subprocess.run(["git", "ls-files", "--error-unmatch", path], cwd=R, capture_output=True).returncode == 0
    except OSError:
        tracked = False
    return "in git index (LFS filter?)" if tracked else "local file, NOT added (git-lfs unavailable)"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(R, "level3", "SOURCE_ARCHIVES.md"))
    a = ap.parse_args()
    rows, total_c, total_u, blockers = [], 0, 0, []
    for app in APPS:
        d = os.path.join(R, "level3", app)
        by = hs.load_yaml(os.path.join(d, "benchmark.yaml")) if os.path.isfile(os.path.join(d, "benchmark.yaml")) else {}
        variants = list(by.get("variants", {}).keys()) if by.get("variants") else [None]
        for v in variants:
            suffix = f".{v}" if v else ""
            lock_p = os.path.join(d, "provenance", f"source.lock{suffix}.yaml")
            lock = hs.load_yaml(lock_p) if os.path.isfile(lock_p) else {}
            ident = by.get("variants", {}).get(v, {}) if v else by.get("source_bundle", {}) or {}
            loc_p = os.path.join(d, "provenance", f"LOC{suffix}.json")
            loc = json.load(open(loc_p))["summary"] if os.path.isfile(loc_p) else {}
            arch = ident.get("archive") or lock.get("archive", {}).get("path", "")
            arch_path = os.path.join(d, arch) if arch else ""
            eq = lock.get("equivalence", [])
            eq_state = "SKIPPED" if eq == "SKIPPED" else ("EQUIVALENT" if eq and all(e.get("status") == "EQUIVALENT" for e in eq) else ("; ".join(f"{e.get('archive_path')}={e.get('status')}" for e in eq) if eq else "not frozen"))
            lic_notes = [n for n in (hs.load_yaml(os.path.join(d, "provenance", f"freeze_spec{suffix}.yaml")) or {}).get("license_notes", []) if "BLOCKER" in n] if os.path.isfile(os.path.join(d, "provenance", f"freeze_spec{suffix}.yaml")) else []
            lic = "BLOCKER (see LICENSES.md)" if lic_notes else ("reviewed, redistributable" if lock else "-")
            if lic_notes:
                blockers.append(f"{app}{suffix}: " + lic_notes[0])
            c, u = ident.get("compressed_size") or 0, ident.get("uncompressed_size") or 0
            total_c += c; total_u += u
            rows.append({"app": f"{app}{suffix}", "archive": arch or "-", "compressed": c, "uncompressed": u, "files": ident.get("file_count") or lock.get("materialized_tree", {}).get("entries", ""),
                         "loc_app": loc.get("application_owned_code_loc", ""), "loc_mod": loc.get("agent_modifiable_code_loc", ""), "loc_total": loc.get("total_materialized_code_loc", ""),
                         "archive_sha": ident.get("archive_sha256") or "", "tree_sha": ident.get("source_tree_sha256") or lock.get("materialized_tree", {}).get("sha256", ""),
                         "lfs": lfs_state(arch_path) if arch_path else "-", "license": lic, "equivalence": eq_state,
                         "upstream": f"{lock.get('upstream', {}).get('tag') or ''} {str(lock.get('upstream', {}).get('commit') or '')[:12]}".strip(), "patches": len(lock.get("patches", []))})
    lines = ["# Level 3 source archives (frozen source bundles)", "",
             f"Generated by `tools/source_archives_report.py` on {__import__('datetime').datetime.now(__import__('datetime').timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')} from `level3/<app>/benchmark.yaml`, `provenance/source.lock*.yaml`, `provenance/LOC*.json` and `provenance/equivalence*.json`.",
             "", "Layout of every bundle: `src/` (application source, patches of the approved series applied) and `deps/` (benchmark-specific source dependencies: pinned git trees or the exact upstream tarballs). `source_tree_sha256` = identity of the extracted tree (algorithm hpcperf-tree-1, `tools/hpcperf_source.py`); `archive sha256` = the zstd archive (hpcperf-tar-1 + zstd -19 single-thread). Materialize with `tools/prepare_benchmark.sh level3 <app> [--variant V]`.",
             "", "| Application | Archive | Compressed | Uncompressed | Files | Source LOC (app-owned / agent-modifiable / total materialized) | Archive SHA256 | Tree SHA256 | LFS ready | License status | Equivalence to validated tree | Upstream | Patches |",
             "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r['app']} | `{r['archive']}` | {hs.human(r['compressed']) if r['compressed'] else '-'} | {hs.human(r['uncompressed']) if r['uncompressed'] else '-'} | {r['files']} | {r['loc_app']} / {r['loc_mod']} / {r['loc_total']} | `{r['archive_sha'][:16]}…` | `{str(r['tree_sha'])[:16]}…` | {r['lfs']} | {r['license']} | {r['equivalence']} | {r['upstream']} | {r['patches']} |")
    lines += ["", f"**Totals**: {len(rows)} archives, {hs.human(total_c)} compressed ({total_c} bytes) = the Git LFS storage needed for one revision of all bundles; {hs.human(total_u)} uncompressed on disk after materialization. Largest archive: {hs.human(max((r['compressed'] for r in rows), default=0))}. A fresh `git clone` + `git lfs pull` transfers the compressed total once; every later re-freeze that changes an archive adds its full size to LFS storage (LFS objects are immutable).", ""]
    if blockers:
        lines += ["## License blockers (decision needed before these archives are pushed)", ""] + [f"- {b}" for b in blockers] + [""]
    lines += ["## Git LFS status", "", "- `.gitattributes`: `level3/*/archives/*.tar.zst filter=lfs diff=lfs merge=lfs -text`.",
              "- `git lfs` is NOT installed on the build node (`git: 'lfs' is not a git command`); no system software was installed. The archives exist as local files and are guarded by a temporary `.gitignore` rule (`level3/*/archives/*.tar.zst`) so that a plain `git add` cannot commit them as ordinary blobs. Once a clone with git-lfs is available: remove that guard line, `git lfs install`, `git add level3/*/archives/*.tar.zst`, verify `git lfs ls-files`, then push -- only after the storage/bandwidth quota of the GitHub organisation has been confirmed for the total above.",
              "- Pointer content for every archive is derivable from `provenance/source.lock*.yaml` (`archive.sha256`, `archive.compressed_size`).", ""]
    with open(a.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
